# 服务器端口配置
server:
  port: 8887


# 全局属性配置
github:
  client:
    id: d02bb3f971ea9947d521
    secret: 2ccb688fbe42a38b83e38ef854d0bcd9727a107d
  redirect:
    url: http://localhost:8887/callback


spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/communitydb?useUnicode=true&useSSL=false&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: cptbtptq123asdqw
  # 关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
  # 开启热部署
  devtools:
    # 热部署生效
    restart.enabled: true
    # 是否支持livereload
    livereload:
      enabled: true
    restart:
      # 设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/*
      # 设置不需要重启的目录
      exclude: static/**,public/**
  # flyway
  # 打开flyway
  flyway:
    enabled: true
    encoding: utf-8
    # sql文件存放位置
    locations: classpath:db/migration
    # 版本记录表格
    table: schemas_version
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    validate-on-migrate: true


mybatis:
  configuration:
    # 启用驼峰自动转换下划线
    map-underscore-to-camel-case: true
  type-aliases-package: xyz.xjydev.community.model
  mapper-locations: classpath:mapper/*.xml


# pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

